### ISSUE TITLE
Running a real time NLP question 

### ISSUE THREAD

**Issue by abhishekmamdapure** [benbogin/spider-schema-gnn-global#4]
Hello, 

I am able to use the [inference code](https://github.com/benbogin/spider-schema-gnn-global) on the dev set and I am able to get the results on the dev set. However, I am not understanding how to use the inference code to get predicted SQL queries on providing input in the form of questions(during deployment). 

Can anyone help me understand how to use the same?

**Comment by benbogin** [comment]
Hey,
I don't have any exact command line configuration at hand but basically you can run AllenNLP's  [simple demo server](https://github.com/allenai/allennlp-server) which gives an interactive web page + api. The predictor class is already implemented in this code base.
