### ISSUE TITLE
difference between spider-schema-gnn and -global 

### ISSUE THREAD

**Issue by jaydeepb-inexture** [benbogin/spider-schema-gnn-global#5]
what is diffrenece in implementation of this and https://github.com/benbogin/spider-schema-gnn
as this implementation shows better result than https://github.com/benbogin/spider-schema-gnn?

**Comment by benbogin** [comment]
The implementation are detailed in the papers: [Representing Schema Structure with Graph Neural Networks for Text-to-SQL Parsing](https://arxiv.org/pdf/1905.06241), [Global Reasoning over Database Structures for Text-to-SQL Parsing](https://arxiv.org/pdf/1908.11214)

The two main contributions in the latter is a global gating mechanism for entities (tables/columns), and a re-ranker.
