### ISSUE TITLE
Link for pre-trained models is dead

### ISSUE THREAD

**Issue by liona24** [benbogin/spider-schema-gnn-global#6]
Hey,

the link in the `README.md` pointing to the Google Drive with the pre-trained model files appears to be dead.

The link for reference:
https://drive.google.com/open?id=1NdSubOVx6IsCpNvkzjTPovsIHEuuebyi

**Comment by benbogin** [comment]
Right, thanks for letting me know!
I will look for the file and re-upload.

**Comment by liona24** [comment]
Thanks for taking care of this. Do you have any updates?

**Comment by benbogin** [comment]
Fixed the link, please let me know if there are any problems downloading/using it.
Thanks!
