### ISSUE TITLE
How to generate executable sql like "query" field of the example?

### ISSUE THREAD

**Issue by shxliang** [benbogin/spider-schema-gnn-global#7]
Code use the 'query_toks_no_value' field of the example which anonymizes values to train and predict, so the model predict results cannot be directly used for execution.
How to generate executable sql like "query" field of the example, can use the  'query_toks' field of the example to train?

**Comment by benbogin** [comment]
Currently the model doesn't handle predicting values. You will need to modify it to allow this - perhaps by attending any of the tokens in the question after decoding an anonymized value token.
