### ISSUE TITLE
Could not find a version that satisfies the requirement allennlp==0.8.2

### ISSUE THREAD

**Issue by jylee-xidian** [benbogin/spider-schema-gnn-global#8]
I'm trying to build the env for runing codes, when i use pip install -r requirements.txt,it cause a bug :
`ERROR: Could not find a version that satisfies the requirement allennlp==0.8.2 (from versions: 0.1a6, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.6.0)
ERROR: No matching distribution found for allennlp==0.8.2
`
I'm use a conda virtul env with python==3.6.5 ,pip version 20.2
So, May i install allennlp by source codes?  How can I solve this problem?

**Comment by benbogin** [comment]
When I run `pip install allennlp==0.8.2` on a clean environment I do not get this error and installation proceeds fine, could you re-check your pip installation?
